// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgicupbqmgaoenyqvhdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnaWN1cGJxbWdhb2VueXF2aGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NjE1NDAsImV4cCI6MjA3ODIzNzU0MH0.l8CFNezPyarqGVTfINTijD68Zy1g4UMg-yk2W0dB7Zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});